### PR TITLE
Use Flags attribute for the VertexUsage enum to build a cache a mask

### PR DESCRIPTION
**Pull request by RUSshy**
So i can build and cache a mask to decide what shader to use

Now i have a question

How to do something similar for Effects ? i need a fast way to know what contains the Effect

### CODE REVIEW

**Comment by RUSshy** [comment]
In libGDX they separate the shader and attributes for the material, they have a class ``Attributes``, and ``Material`` wich extends the ``Attributes`` class wich is just a collection of ``Attribute``, it is type safe so they can build a mask when they set an attribute

```
material.set(new ColorAttribute(ColorAttribute.Diffuse, myColor))
```

I can send PR for that, but i don't know if it is how you want 3D to be in ultraviolet

**Comment by tlgkccampbell** [comment]
I'm not sure this really captures all the possibilities. How does this work if, for example, my model has two separate texture channels? In other words, how would I recognize:

```cs
public static readonly VertexDeclaration VertexDeclaration = new VertexDeclaration(new[] {
    new VertexElement(0, VertexFormat.Vector2, VertexUsage.TextureCoordinate, 0),
    new VertexElement(8, VertexFormat.Vector2, VertexUsage.TextureCoordinate, 1),
});
```

**Comment by RUSshy** [comment]
Oh you are right !!

**Comment by RUSshy** [comment]
I can't think of a good method for this unfortunatly

I wanted to do something automatic, but i guess i'll have to hardcode shader selection for the moment

**Pull request closed without merging**
