### PR TITLE
Update to .NET6

### PR DESCRIPTION
**Pull request by jayrulez**
- Removed NETCORE 2

Let me know if this is of interest.

### CODE REVIEW

**Comment by tlgkccampbell** [comment]
I appreciate the considerable effort you've put into this. However, I have neither the time nor, to be honest, the desire to continue to work on this project, and I feel like merging this PR would mean taking on a level of responsibility for supporting it that I'm not prepared to accept. I've already dismantled my build infrastructure and used it for other things, so even just publishing this to NuGet would require nontrivial effort.

Would you be interested in just taking over the project as a whole?

**Comment by jayrulez** [comment]
I've thought about it for a few days. I'm positive that I won't be able to afford the time to maintain the project in the near or medium term. Thanks for the consideration though. My primary motivation for experimenting with UV was the UI framework which I think is quite impressive. 

If I change my mind in the future then I will let you know.

**Comment by jayrulez** [comment]
@tlgkccampbell was android supposed to support runtime code generation?

I updated Android to use the net6.0-android TFM but the Sandbox android app is crashing on some UVPF stuff. If I let it return false for the runtime code generation check then the sample will work. Perhaps android supported runtime code generation under the original Mono runtime but not under CoreCLR?

**Comment by jayrulez** [comment]
I found the problem. For some reason on android, the Expression.Property method cannot locate the AutoRelease property on RoutedEventData (probably because it is protected internal). If I change the property to public then it works.

**Comment by jayrulez** [comment]
@tlgkccampbell I would like to revisit this again.

After months of using and experimenting with the framework, I've become quite familiar with most parts and I've gained much confidence in being able to maintain and evolve it. I'm open to taking over the project if the offer still exists.

**Comment by tlgkccampbell** [comment]
I still have no time or desire to get back into this project, so by all means. I'll transfer ownership of the repository to you. I hope it serves you well.

**Comment by tlgkccampbell** [comment]
GitHub is telling me that you already have an Ultraviolet repository, so I'm guessing you need to delete your fork first?

**Comment by jayrulez** [comment]
I just created an organization for this.

Please transfer here: https://github.com/UltravioletFramework instead of my personal account.

**Comment by tlgkccampbell** [comment]
OK. It looks like you need to give me permissions to create repositories for this org before it'll let this go through.

**Comment by jayrulez** [comment]
Done, you should see an invitation in your email. If not, you can just click the organization link I think.

**Comment by IceReaper** [comment]
Wonderful to see this again alive! <3

**Comment by jayrulez** [comment]
Is it also possible for you to add me as an owner on the nuget packages so I will be able to update them?

My username on nuget.org is jayrulez

**Comment by tlgkccampbell** [comment]
OK, I think I got everything. Let me know if I missed something.

**Comment by jayrulez** [comment]
Yes, it looks like you got everything. Thanks a lot!

In the future, do you mind if I ask questions about certain aspects of the framework?
I would not ask you anything where you would need to invest much effort to give an answer.

**Comment by tlgkccampbell** [comment]
By all means ask, but it's been a very long time since I've thought about Ultraviolet at all, so I'm afraid I may have forgotten many of the answers... 😬

**Comment by jayrulez** [comment]
@tlgkccampbell so here's my first question:
The SpriteFont related files here https://github.com/UltravioletFramework/ultraviolet/tree/main/Source/Ultraviolet.OpenGL/Graphics/Graphics2D do not seem to do anything that's specific to OpenGL and could be re-used with another hypothetical graphics backend. Was there a particular reason you placed them there as opposed to https://github.com/UltravioletFramework/ultraviolet/tree/main/Source/Ultraviolet/Graphics/Graphics2D?

**Comment by jayrulez** [comment]
Also, it seems I didn't get access to the Ultraviolet.FMOD.Native package on nuget.org

Could you please add me to that one as well?

**Comment by tlgkccampbell** [comment]
> @tlgkccampbell so here's my first question: The SpriteFont related files here https://github.com/UltravioletFramework/ultraviolet/tree/main/Source/Ultraviolet.OpenGL/Graphics/Graphics2D do not seem to do anything that's specific to OpenGL and could be re-used with another hypothetical graphics backend. Was there a particular reason you placed them there as opposed to https://github.com/UltravioletFramework/ultraviolet/tree/main/Source/Ultraviolet/Graphics/Graphics2D?

Well, `OpenGLSpriteBatchEffect` is implementation-specific because it has a dependency on GLSL shaders. Other than that, I think I may have originally had some intention to preprocess texture data in a way that was more specific to OpenGL, but I guess I never ended up doing it. Sprites are very old and in fact a large part of the code predates Ultraviolet itself, so I wouldn't be surprised if they're full of decisions that made sense at one point but don't anymore.

**Pull request closed without merging**
